version: "3.7"

services:
  traefik:
    image: "traefik:v2.4"

    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      # - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - web

  project:
    container_name: dockerized-react-app

    build:
      context: .
      dockerfile: Dockerfile-prod

    ports:
      - '3001:80'

    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`landingpage.cayama.com.br`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      

networks:
  web:
    external: true